name: ci
on: [push, pull_request]
permissions: read-all
jobs:
  build-and-test:
    strategy:
      matrix:
        working-directory: [., cmd/climate, cmd/examples]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - working-directory: ${{ matrix.working-directory }}
        run: |
          go build -v ./...
          go test  -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
